{
	"version": 1661879094,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/awg/sprite7-sheet0.png",
		"images/awg/sprite7-sheet1.png",
		"images/awg/sprite-sheet0.png",
		"images/awg/sprite2-sheet0.png",
		"images/awg/sprite3-sheet0.png",
		"images/awg/sprite4-sheet0.png",
		"images/awg/sprite5-sheet0.png",
		"images/awg/sprite58-sheet0.png",
		"images/awg/sprite6-sheet0.png",
		"images/awg/sprite36-sheet0.png",
		"images/awg/sprite8-sheet0.png",
		"images/awg/sprite9-sheet0.png",
		"images/awg/sprite10-sheet0.png",
		"images/awg/sprite11-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}